/*
 * GeneralPurposeProver.java
 * ---------------------------------
 * Copyright (c) 2024
 * RESOLVE Software Research Group
 * School of Computing
 * Clemson University
 * All rights reserved.
 * ---------------------------------
 * This file is subject to the terms and conditions defined in
 * file 'LICENSE.txt', which is part of this source code package.
 */
package edu.clemson.rsrg.nProver;

import edu.clemson.rsrg.absyn.declarations.moduledecl.*;
import edu.clemson.rsrg.absyn.expressions.Exp;
import edu.clemson.rsrg.init.CompileEnvironment;
import edu.clemson.rsrg.init.flag.Flag;
import edu.clemson.rsrg.init.flag.FlagDependencies;
import edu.clemson.rsrg.init.output.OutputListener;
import edu.clemson.rsrg.nProver.output.VCProverResult;
import edu.clemson.rsrg.nProver.registry.CongruenceClassRegistry;
import edu.clemson.rsrg.nProver.utilities.Elaborator;
import edu.clemson.rsrg.nProver.utilities.theorems.ElaborationRules;
import edu.clemson.rsrg.nProver.utilities.theorems.TheoremStore;
import edu.clemson.rsrg.nProver.utilities.treewakers.AbstractRegisterSequent;
import edu.clemson.rsrg.nProver.utilities.treewakers.RegisterAntecedent;
import edu.clemson.rsrg.nProver.utilities.treewakers.RegisterSuccedent;
import edu.clemson.rsrg.parsing.data.LocationDetailModel;
import edu.clemson.rsrg.statushandling.Fault;
import edu.clemson.rsrg.statushandling.FaultType;
import edu.clemson.rsrg.treewalk.TreeWalker;
import edu.clemson.rsrg.typeandpopulate.entry.TheoremEntry;
import edu.clemson.rsrg.typeandpopulate.symboltables.ModuleScope;
import edu.clemson.rsrg.typeandpopulate.typereasoning.TypeGraph;
import edu.clemson.rsrg.vcgeneration.VCGenerator;
import edu.clemson.rsrg.vcgeneration.sequents.Sequent;
import edu.clemson.rsrg.vcgeneration.utilities.VerificationCondition;

import java.util.*;
import java.util.concurrent.TimeUnit;

import org.stringtemplate.v4.ST;
import org.stringtemplate.v4.STGroup;
import org.stringtemplate.v4.STGroupFile;
import static edu.clemson.rsrg.vcgeneration.VCGenerator.FLAG_VERIFY_VC;
import static edu.clemson.rsrg.misc.DebuggerHelper.debugLog;

/**
 * <p>
 * This class is a general purpose prover that attempts to prove the {@code VCs} generated by {@link VCGenerator}.
 * </p>
 *
 * @author Yu-Shan Sun
 * @author Nicodemus Msafiri J. M.
 *
 * @version 1.0
 */
public class GeneralPurposeProver {

    // ===========================================================
    // Member Fields
    // ===========================================================

    /**
     * <p>
     * The current job's compilation environment that stores all necessary objects and flags.
     * </p>
     */
    private final CompileEnvironment myCompileEnvironment;

    /**
     * <p>
     * The module scope for the file we are generating automated proofs for.
     * </p>
     */
    private final ModuleScope myCurrentModuleScope;

    /**
     * <p>
     * The number of tries before halting the automated prover
     * </p>
     */
    private final int myNumTriesBeforeHalting;

    /**
     * <p>
     * The various different output listeners that are expecting an update.
     * </p>
     */
    private final List<OutputListener> myOutputListeners;

    /**
     * <p>
     * The number of milliseconds before stopping the prove for a VC.
     * </p>
     */
    private final long myTimeout;

    /**
     * <p>
     * The total number of milliseconds spent proving VCs in this file.
     * </p>
     */
    private long myTotalElapsedTime;

    /**
     * <p>
     * This is the math type graph that indicates relationship between different math types.
     * </p>
     */
    private final TypeGraph myTypeGraph;

    /**
     * <p>
     * The module's final list of verification conditions.
     * </p>
     */
    private final List<VerificationCondition> myVerificationConditions;

    // -----------------------------------------------------------
    // Output-Related
    // -----------------------------------------------------------

    /**
     * <p>
     * String template groups for storing all the prover details.
     * </p>
     */
    private final STGroup mySTGroup;

    /**
     * <p>
     * String template for the prover generation details model.
     * </p>
     */
    private final ST myProofGenDetailsModel;

    /**
     * <p>
     * A list containing the prover results for each VC.
     * </p>
     */
    private final List<VCProverResult> myVCProverResults;

    // ===========================================================
    // Flag Strings
    // ===========================================================

    public static final String FLAG_SECTION_NAME = "Prover";
    private static final String FLAG_DESC_GP_PROVER = "General Purpose Automated Prover"; // DESC -- Description
    private static final String FLAG_DESC_PROVER_NUMTRIES = "Number of Failed VCs Before Halting the Prover.";
    private static final String[] NUMTRIES_ARGS = { "numtries" };
    private static final String FLAG_DESC_PROVER_TIMEOUT = "Number of Milliseconds to Use as a Timeout Before Skipping Proving a VC.";
    private static final String[] FLAG_TIMEOUT_ARGS = { "milliseconds" };

    // ===========================================================
    // Flags
    // ===========================================================

    /**
     * Tells the compiler to prove the sequent VCs
     */
    public static final Flag FLAG_PROVE = new Flag(FLAG_SECTION_NAME, "sprove", FLAG_DESC_GP_PROVER); // sequent
    // prove

    /**
     * <p>
     * Specifies number of milliseconds before skipping proving a VC.
     * </p>
     */
    private static final Flag FLAG_TIMEOUT = new Flag(FLAG_SECTION_NAME, "timeout", FLAG_DESC_PROVER_TIMEOUT,
            FLAG_TIMEOUT_ARGS, Flag.Type.HIDDEN);

    /**
     * <p>
     * Specify number of failed VCs before halting the prover.
     * </p>
     */
    private static final Flag FLAG_NUMTRIES = new Flag(FLAG_SECTION_NAME, "num_tries", FLAG_DESC_PROVER_NUMTRIES,
            NUMTRIES_ARGS, Flag.Type.HIDDEN);

    /**
     * <p>
     * Add all the required and implied flags for the {@code GeneralPurposeProver}.
     * </p>
     */
    public static void setUpFlags() {
        FlagDependencies.addImplies(FLAG_PROVE, FLAG_VERIFY_VC); // adding prove flag, also add verify VC flag
        FlagDependencies.addRequires(FLAG_TIMEOUT, FLAG_PROVE);
        FlagDependencies.addRequires(FLAG_NUMTRIES, FLAG_PROVE);
    }

    // ===========================================================
    // Constructors
    // ===========================================================

    /**
     * <p>
     * This creates an instance of the general purpose automated prover.
     * </p>
     *
     * @param vcs
     *            The list of VCs to be proven.
     * @param moduleScope
     *            The module scope associated with {@code name}.
     * @param compileEnvironment
     *            The current job's compilation environment that stores all necessary objects and flags.
     */
    public GeneralPurposeProver(List<VerificationCondition> vcs, ModuleScope moduleScope,
            CompileEnvironment compileEnvironment) {
        myCompileEnvironment = compileEnvironment;
        myCurrentModuleScope = moduleScope;
        myOutputListeners = myCompileEnvironment.getOutputListeners();
        mySTGroup = new STGroupFile("templates/nProverVerboseOutput.stg");
        myTotalElapsedTime = 0;
        myTypeGraph = compileEnvironment.getTypeGraph();
        myVCProverResults = new ArrayList<>(vcs.size());
        myVerificationConditions = vcs;
        myProofGenDetailsModel = mySTGroup.getInstanceOf("outputProofGenDetails");

        // Timeout
        if (myCompileEnvironment.flags.isFlagSet(FLAG_TIMEOUT)) {
            myTimeout = Long.parseLong(myCompileEnvironment.flags.getFlagArgument(FLAG_TIMEOUT, "milliseconds"));
        } else {
            myTimeout = 5000;
        }

        // Number of Tries
        if (myCompileEnvironment.flags.isFlagSet(FLAG_NUMTRIES)) {
            myNumTriesBeforeHalting = Integer
                    .parseInt(myCompileEnvironment.flags.getFlagArgument(FLAG_NUMTRIES, "numtries"));
        } else {
            myNumTriesBeforeHalting = -1;
        }

        // Store verbose output about this module
        ST header;
        ModuleDec moduleDec = myCurrentModuleScope.getDefiningElement();
        header = switch (moduleDec) {
            case ConceptModuleDec ignored ->
                    mySTGroup.getInstanceOf("outputConceptHeader").add("conceptName", moduleDec.getName().getName());
            case ConceptRealizModuleDec conceptRealizModuleDec -> mySTGroup.getInstanceOf("outputConceptRealizHeader")
                    .add("realizName", moduleDec.getName().getName())
                    .add("conceptName", conceptRealizModuleDec.getConceptName().getName());
            case EnhancementModuleDec enhancementModuleDec -> mySTGroup.getInstanceOf("outputEnhancementHeader")
                    .add("enhancementName", moduleDec.getName().getName())
                    .add("conceptName", enhancementModuleDec.getConceptName().getName());
            case EnhancementRealizModuleDec enhancementRealizModuleDec -> mySTGroup
                    .getInstanceOf("outputEnhancementRealizHeader").add("realizName", moduleDec.getName().getName())
                    .add("enhancementName", enhancementRealizModuleDec.getEnhancementName().getName())
                    .add("conceptName", enhancementRealizModuleDec.getConceptName().getName());
            default ->
                    mySTGroup.getInstanceOf("outputFacilityHeader").add("facilityName", moduleDec.getName().getName());
        };
        myProofGenDetailsModel.add("fileHeader", header.render());
    }

    // ===========================================================
    // Public Methods
    // ===========================================================

    /**
     * <p>
     * This method returns the prover setting for how many unproved {@code VCs} we allow before halting.
     * </p>
     *
     * @return The number of tries with -1 indicating that we attempt to prove all VCs.
     */
    public final int getNumTriesBeforeHalting() {
        return myNumTriesBeforeHalting;
    }

    /**
     * <p>
     * This method returns the prover setting for the maximum amount of time we can spend proving each {@code VC}.
     * </p>
     *
     * @return The time that can be spent proving each {@code VC} in ms.
     */
    public final long getTimeout() {
        return myTimeout;
    }

    /**
     * <p>
     * This method returns the total elapsed time that we spent proving {@code VCs} in this {@link ModuleDec}.
     * </p>
     *
     * @return The total elapsed time in ms.
     */
    public final long getTotalElapsedTime() {
        return myTotalElapsedTime;
    }

    /**
     * <p>
     * This method returns a list containing the proof details for each {@code VC}.
     * </p>
     *
     * @return A {@link List} of {@link VCProverResult}.
     */
    public final List<VCProverResult> getVCProverResults() {
        return myVCProverResults;
    }

    /**
     * <p>
     * This method returns the verbose mode output with how we attempted to prove each {@code VCs} in this
     * {@link ModuleDec}.
     * </p>
     *
     * @return A string containing lots of details.
     */
    public final String getVerboseModeOutput() {
        return myProofGenDetailsModel.render();
    }

    /**
     * <p>
     * This method runs the general purpose prover on all the VCs.
     * </p>
     */
    public void proveVCs() {
        debugLog("Logging Level: Debug");

        // Keep track to total elapsed time and number of unproved/timed out VCs
        myTotalElapsedTime = System.currentTimeMillis();

        // Use the new TheoremStore to preload theorems for fast lookup.
        TheoremStore theoremStore = new TheoremStore(myCurrentModuleScope);

        // Loop through each of the VCs and attempt to prove them
        for (VerificationCondition vc : myVerificationConditions) {
            // if (vc.getName().equals("0_1") || vc.getName().equals("1_1"))
            // continue;
            // if (!vc.getName().equals("0_3"))
            // continue;
            Map<String, Integer> expLabels = new LinkedHashMap<>();
            // revert ExpLabels to before Senior Project Team things
            // NM: 0, 1 are spared for <= (1), = (2), etc., the list can expand with more reflexive operators
            // preload <=, = into the map
            expLabels.put("<=", AbstractRegisterSequent.OP_LESS_THAN_OR_EQUALS);
            expLabels.put("=", AbstractRegisterSequent.OP_EQUALS);

            // TODO: Create new threads for each VC, and kill them if they run for too long
            List<String> mappings = new ArrayList<>();
            mappings.add("");
            mappings.add("<=");
            mappings.add("=");

            debugLog("====================================== VC #" + vc.getName()
                    + " =====================================");
            debugLog(vc);
            // Store the start time for generating proofs for this VC
            long startTime = System.nanoTime();
            // Obtain the sequent to be proved
            Sequent sequent = vc.getSequent();

            // Create a registry and label map
            CongruenceClassRegistry registry = new CongruenceClassRegistry(1000, 1000, 1000, 1000);

            // Visit antecedents
            RegisterAntecedent regAntecedent = new RegisterAntecedent(registry, expLabels, 3, mappings);
            for (Exp exp : sequent.getAntecedents()) {
                TreeWalker.visit(regAntecedent, exp);
            }

            boolean isProved = false;

            // Visit consequents
            RegisterSuccedent regConsequent = new RegisterSuccedent(regAntecedent.getRegistry(),
                    regAntecedent.getExpLabels(), regAntecedent.getNextLabel(), mappings);
            for (Exp exp : sequent.getConcequents()) {
                TreeWalker.visit(regConsequent, exp);
                if (exp.toString().equals("true")) {
                    isProved = true;
                    break;
                }
            }

            isProved |= registry.checkIfProved();

            Set<String> theoremsUsed = new LinkedHashSet<>(); // Used for printing results, not needed to prove
            if (!isProved) {
                debugLog("=== Initial Registry ===");
                debugLog(registry.toPrettyString(mappings));

                Elaborator elaborator = new Elaborator(registry, expLabels, mappings);
                Set<TheoremEntry> relevantTheorems = theoremStore.getRelevantTheoremsByOperators(expLabels.keySet());
                ElaborationRules rules = new ElaborationRules(relevantTheorems);
                printRelevant(rules, relevantTheorems, vc.getName());
                for (int l = 0; l < 5; l++) {
                    // List<RuleInstance> ruleInstances = elaborator.elaborate(rules.getMyElaborationRules());

                    debugLog("============ VC #" + vc.getName() + " (Printed again for reference) "
                            + " ===============");
                    debugLog(vc);

                    debugLog("============ [Attempt " + l + "] Elaboration & Matching (VC #" + vc.getName()
                            + ") ===============");

                    theoremsUsed.addAll(elaborator.elaborateAndApply(rules.getMyElaborationRules()));
                    isProved |= registry.checkIfProved();
                    debugLog("=== Registry after Elaboration Attempt ===");
                    debugLog(registry.toPrettyString(mappings));
                    debugLog("Proved: " + registry.checkIfProved());
                    if (isProved) {
                        break;
                    }
                }
            }

            // Store the end time for generating proofs for this VC
            long endTime = System.nanoTime();

            // Store the prover results for this VC
            myVCProverResults.add(new VCProverResult(vc,
                    TimeUnit.MILLISECONDS.convert(endTime - startTime, TimeUnit.NANOSECONDS), isProved, false, false));

            // Store the verbose proof detail for this VC
            String result = isProved ? "Proved" : "Not Proved";
            storeVCProofVerboseDetail(vc, result, registry, expLabels, mappings, theoremsUsed);
            if (isProved) {
                System.out.print("[VC #" + vc.getName() + "]: \u001B[42m   Proved   \u001B[49m " + vc);
            } else {
                System.out.print("[VC #" + vc.getName() + "]: \u001B[41m Not Proved \u001B[49m " + vc);
            }
        }

        // Compute the total elapsed time in generating proofs for the VCs in this
        // module
        myTotalElapsedTime = System.currentTimeMillis() - myTotalElapsedTime;

    }

    public void printRelevant(ElaborationRules rules, Set<TheoremEntry> relevantTheorems, String vcNum) {
        debugLog("=========================== Relevant Theorems (VC #" + vcNum + ") ===========================");
        int j = 0;
        for (TheoremEntry te : relevantTheorems) {
            debugLog("Theorem " + vcNum + "_" + j + ": " + "\u001B[33m" + te.getName() + "\u001B[0m" + " (from "
                    + "\u001B[34m" + te.getSourceModuleIdentifier() + "\u001B[0m" + ")");
            debugLog(te.getAssertion());
            debugLog("\n");
            j++;
        }

        debugLog("============ Elaboration Rules (VC #" + vcNum + ") ===============");
        debugLog(rules);
    }

    // ===========================================================
    // Private Methods
    // ===========================================================

    /**
     * <p>
     * An helper method that stores verbose detail about proving this {@code VC}.
     * </p>
     *
     * @param vc
     *            The {@link VerificationCondition} we have attempted to prove.
     * @param result
     *            The prover results.
     * @param registry
     *            The congruence class registry used on this {@code VC}.
     * @param expLabels
     *            The expression labels assigned to the expressions in this {@code VC}.
     * @param mappings
     *            The list of labels with indexes as its cluster ID
     * @param theoremsUsed
     *            The set of theorems used
     */
    private void storeVCProofVerboseDetail(VerificationCondition vc, String result, CongruenceClassRegistry registry,
            Map<String, Integer> expLabels, List<String> mappings, Set<String> theoremsUsed) {
        // Create a model for adding all the details associated with this VC.
        LocationDetailModel detailModel = vc.getLocationDetailModel();
        ST vcModel = mySTGroup.getInstanceOf("outputVC");
        vcModel.add("vcNum", vc.getName());

        // Add additional detail if this VC has impacting reduction
        if (vc.getHasImpactingReductionFlag()) {
            vcModel.add("hasImpactingReduction", true);
        }

        // Warn the user if are missing the LocationDetailModel
        if (detailModel != null) {
            vcModel.add("location", detailModel.getDestinationLoc());
            vcModel.add("locationDetail", detailModel.getDetailMessage());
        } else {
            Fault vcGenMissingInfo = new Fault(FaultType.MISSING_INFO_VC_GEN, vc.getLocation(),
                    "[FileOutputListener] VC " + vc.getName() + " is missing information about "
                            + "how this VC got generated.",
                    false);
            myCompileEnvironment.getStatusHandler().registerAndStreamFault(vcGenMissingInfo);
        }

        // Output the associated sequent
        Sequent sequent = vc.getSequent();
        ST sequentModel = mySTGroup.getInstanceOf("outputSequent");
        sequentModel.add("consequents", sequent.getConcequents());
        sequentModel.add("antecedents", sequent.getAntecedents());

        // Add this sequent to our vc model
        vcModel.add("sequent", sequentModel.render());

        /*
         * // Store the congruence class registry array information ST ccRegistryArraysModel =
         * mySTGroup.getInstanceOf("outputCCRegistryArrays"); ccRegistryArraysModel.add("clusterArguments",
         * registry.getClusterArgArray()); ccRegistryArraysModel.add("clusters", registry.getClusterArray());
         * ccRegistryArraysModel.add("plantations", registry.getStandArray()); // plantations are now stands
         * ccRegistryArraysModel.add("classes", registry.getCongruenceClassArray());
         */
        StringBuilder niceTheorems = new StringBuilder();
        for (String theorem : theoremsUsed) {
            niceTheorems.append("- ").append(theorem).append("\n");
        }

        // Add the VC to the VC proof detail model
        ST vcProofDetailModel = mySTGroup.getInstanceOf("outputVCProofDetails");
        vcProofDetailModel.add("vcNum", vc.getName());
        vcProofDetailModel.add("vc", vcModel.render());
        vcProofDetailModel.add("result", result);
        vcProofDetailModel.add("expLabels", expLabels);
        vcProofDetailModel.add("registryArrays", registry.toMarkdownFriendlyString(mappings));// ccRegistryArraysModel.render());
        vcProofDetailModel.add("theoremsUsed", niceTheorems.toString());

        // Add VC proof detail model to prover generation details
        myProofGenDetailsModel.add("vcProofDetails", vcProofDetailModel.render());
    }

}
